### ISSUE TITLE
Data Lake Deployment Failure from ARM

### ISSUE THREAD

**Issue by drcrook1** [drcrook1/BioInformatics#20]
OPERATION ID2D5A2CABA9E6BDBD
TRACKING ID94d8c93d-f53f-425b-b84b-a6061b6c15d1
STATUSNotFound
PROVISIONING STATEFailed
TIMESTAMP6/13/2016, 2:59:34 PM
DURATIONPT0.2432335S
TYPEMicrosoft.DataLakeStore/accounts
RESOURCE ID/subscriptions/6f8e1070-db11-4a3d-8065-e11b395fe219/resourceGroups/BioInfo/providers/Microsoft.DataLakeStore/accounts/bioinfodl
STATUSMESSAGE{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'."
  }
}
RESOURCEbioinfodl

**Comment by rahulrai-in** [comment]
Fixed.
