### ISSUE TITLE
Service Bus Deployment Failure

### ISSUE THREAD

**Issue by drcrook1** [drcrook1/BioInformatics#21]
OPERATION ID9839BC298409E121
TRACKING ID2d7aa3c7-e22f-4794-89be-6395fbb1709d
STATUSBadRequest
PROVISIONING STATEFailed
TIMESTAMP6/13/2016, 2:59:42 PM
DURATIONPT3.1281056S
TYPEMicrosoft.ServiceBus/namespaces
RESOURCE ID/subscriptions/6f8e1070-db11-4a3d-8065-e11b395fe219/resourceGroups/BioInfo/providers/Microsoft.ServiceBus/namespaces/bioinfoservicebus
STATUSMESSAGE{
  "error": {
    "message": "Namespace status can only be changed to Active Or Disabled.",
    "code": "BadRequest"
  }
}
RESOURCEbioinfoservicebus

**Comment by rahulrai-in** [comment]
Tested the new deployment script. Seems like an intermittent issue.
