### ISSUE TITLE
Web Skeleton

### ISSUE THREAD

**Issue by drcrook1** [drcrook1/BioInformatics#3]
BioInfo.Web.Api
---> Web Apis
BioInfo.Web.Admin
---> Admin Portal for adding new devices, managing devices, users etc
BioInfo.Web.External
---> Externally Facing web portal with charts etc.

**Comment by joescars** [comment]
Am I still assigned to this task or has it been re-assigned?

**Comment by drcrook1** [comment]
I'll take ownership till Dave comes on line.

**Comment by drcrook1** [comment]
Skeleton Complete
