### ISSUE TITLE
Infrastructure Automation Skeleton

### ISSUE THREAD

**Issue by drcrook1** [drcrook1/BioInformatics#4]
BioInfo.Automation.*

Naming should be left up to Blain or ITPros

This should contain empty scripts and deployment instructions.
1.  Deploy All Infrastructure
- Azure Stream Analytics
- Blob Storage
- Azure Machine Learning
- 3 Web Applications
  (APIs, Admin & External)
- IoT Hub

**Comment by blainbar** [comment]
We will document this for evangelism efforts.

**Comment by blainbar** [comment]
Making changes as Rahul updates
